version: 2.1

executors:
  default-executor:
    docker:
      - image: cypress/base:10
jobs:
  build:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Build'
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: .
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
