version: 2.0
orbs:
  node: circleci/node@3.0.0
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install-dependencies
      - build
      - deploy:
          requires:
            - build
