version: 2.1

executors:
  default-executor:
    docker:
      - image: cypress/base:10
jobs:
  install-dependencies:
    executor: default-executor
    steps:
      - checkout
  build:
    executor: default-executor
    steps:
      - run:
          name: 'Build'
          command: npm run build
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - install-dependencies
      - build
